import typing as t

import polars as pl

# The full schema was produced via gedi_geoparquet.polars._infer_schema.
# Although we're selecting only a subset of columns, we're leaving the unused
# columns in comments so we have a full reference of what's available.
SCHEMA: t.Final = pl.Schema(
    {
        # "ancillary/l2a_alg_count": pl.UInt8(),
        # "beam": pl.UInt16(),
        # "channel": pl.UInt8(),
        "degrade_flag": pl.UInt8(),
        "delta_time": pl.Float64(),
        "digital_elevation_model": pl.Float32(),
        "digital_elevation_model_srtm": pl.Float32(),
        # "elev_highestreturn": pl.Float32(),
        "elev_lowestmode": pl.Float32(),
        # "elevation_bias_flag": pl.UInt8(),
        # "elevation_bin0_error": pl.Float32(),
        "energy_total": pl.Float32(),
        "geolocation/elev_highestreturn_a1": pl.Float32(),
        "geolocation/elev_highestreturn_a2": pl.Float32(),
        "geolocation/elev_highestreturn_a3": pl.Float32(),
        "geolocation/elev_highestreturn_a4": pl.Float32(),
        "geolocation/elev_highestreturn_a5": pl.Float32(),
        "geolocation/elev_highestreturn_a6": pl.Float32(),
        # "geolocation/elev_lowestmode_a1": pl.Float32(),
        # "geolocation/elev_lowestmode_a2": pl.Float32(),
        # "geolocation/elev_lowestmode_a3": pl.Float32(),
        # "geolocation/elev_lowestmode_a4": pl.Float32(),
        # "geolocation/elev_lowestmode_a5": pl.Float32(),
        # "geolocation/elev_lowestmode_a6": pl.Float32(),
        # "geolocation/elev_lowestreturn_a1": pl.Float32(),
        # "geolocation/elev_lowestreturn_a2": pl.Float32(),
        # "geolocation/elev_lowestreturn_a3": pl.Float32(),
        # "geolocation/elev_lowestreturn_a4": pl.Float32(),
        # "geolocation/elev_lowestreturn_a5": pl.Float32(),
        # "geolocation/elev_lowestreturn_a6": pl.Float32(),
        # "geolocation/elevation_1gfit": pl.Float32(),
        # "geolocation/elevs_allmodes_a1": pl.List(pl.Float32()),
        # "geolocation/elevs_allmodes_a2": pl.List(pl.Float32()),
        # "geolocation/elevs_allmodes_a3": pl.List(pl.Float32()),
        # "geolocation/elevs_allmodes_a4": pl.List(pl.Float32()),
        # "geolocation/elevs_allmodes_a5": pl.List(pl.Float32()),
        # "geolocation/elevs_allmodes_a6": pl.List(pl.Float32()),
        # "geolocation/energy_lowestmode_a1": pl.Float32(),
        # "geolocation/energy_lowestmode_a2": pl.Float32(),
        # "geolocation/energy_lowestmode_a3": pl.Float32(),
        # "geolocation/energy_lowestmode_a4": pl.Float32(),
        # "geolocation/energy_lowestmode_a5": pl.Float32(),
        # "geolocation/energy_lowestmode_a6": pl.Float32(),
        # "geolocation/lat_highestreturn_a1": pl.Float64(),
        # "geolocation/lat_highestreturn_a2": pl.Float64(),
        # "geolocation/lat_highestreturn_a3": pl.Float64(),
        # "geolocation/lat_highestreturn_a4": pl.Float64(),
        # "geolocation/lat_highestreturn_a5": pl.Float64(),
        # "geolocation/lat_highestreturn_a6": pl.Float64(),
        # "geolocation/lat_lowestmode_a1": pl.Float64(),
        # "geolocation/lat_lowestmode_a2": pl.Float64(),
        # "geolocation/lat_lowestmode_a3": pl.Float64(),
        # "geolocation/lat_lowestmode_a4": pl.Float64(),
        # "geolocation/lat_lowestmode_a5": pl.Float64(),
        # "geolocation/lat_lowestmode_a6": pl.Float64(),
        # "geolocation/lat_lowestreturn_a1": pl.Float64(),
        # "geolocation/lat_lowestreturn_a2": pl.Float64(),
        # "geolocation/lat_lowestreturn_a3": pl.Float64(),
        # "geolocation/lat_lowestreturn_a4": pl.Float64(),
        # "geolocation/lat_lowestreturn_a5": pl.Float64(),
        # "geolocation/lat_lowestreturn_a6": pl.Float64(),
        # "geolocation/latitude_1gfit": pl.Float64(),
        # "geolocation/lats_allmodes_a1": pl.List(pl.Float64()),
        # "geolocation/lats_allmodes_a2": pl.List(pl.Float64()),
        # "geolocation/lats_allmodes_a3": pl.List(pl.Float64()),
        # "geolocation/lats_allmodes_a4": pl.List(pl.Float64()),
        # "geolocation/lats_allmodes_a5": pl.List(pl.Float64()),
        # "geolocation/lats_allmodes_a6": pl.List(pl.Float64()),
        # "geolocation/lon_highestreturn_a1": pl.Float64(),
        # "geolocation/lon_highestreturn_a2": pl.Float64(),
        # "geolocation/lon_highestreturn_a3": pl.Float64(),
        # "geolocation/lon_highestreturn_a4": pl.Float64(),
        # "geolocation/lon_highestreturn_a5": pl.Float64(),
        # "geolocation/lon_highestreturn_a6": pl.Float64(),
        # "geolocation/lon_lowestmode_a1": pl.Float64(),
        # "geolocation/lon_lowestmode_a2": pl.Float64(),
        # "geolocation/lon_lowestmode_a3": pl.Float64(),
        # "geolocation/lon_lowestmode_a4": pl.Float64(),
        # "geolocation/lon_lowestmode_a5": pl.Float64(),
        # "geolocation/lon_lowestmode_a6": pl.Float64(),
        # "geolocation/lon_lowestreturn_a1": pl.Float64(),
        # "geolocation/lon_lowestreturn_a2": pl.Float64(),
        # "geolocation/lon_lowestreturn_a3": pl.Float64(),
        # "geolocation/lon_lowestreturn_a4": pl.Float64(),
        # "geolocation/lon_lowestreturn_a5": pl.Float64(),
        # "geolocation/lon_lowestreturn_a6": pl.Float64(),
        # "geolocation/longitude_1gfit": pl.Float64(),
        # "geolocation/lons_allmodes_a1": pl.List(pl.Float64()),
        # "geolocation/lons_allmodes_a2": pl.List(pl.Float64()),
        # "geolocation/lons_allmodes_a3": pl.List(pl.Float64()),
        # "geolocation/lons_allmodes_a4": pl.List(pl.Float64()),
        # "geolocation/lons_allmodes_a5": pl.List(pl.Float64()),
        # "geolocation/lons_allmodes_a6": pl.List(pl.Float64()),
        # "geolocation/num_detectedmodes_a1": pl.UInt8(),
        # "geolocation/num_detectedmodes_a2": pl.UInt8(),
        # "geolocation/num_detectedmodes_a3": pl.UInt8(),
        # "geolocation/num_detectedmodes_a4": pl.UInt8(),
        # "geolocation/num_detectedmodes_a5": pl.UInt8(),
        # "geolocation/num_detectedmodes_a6": pl.UInt8(),
        # "geolocation/quality_flag_a1": pl.UInt8(),
        # "geolocation/quality_flag_a2": pl.UInt8(),
        # "geolocation/quality_flag_a3": pl.UInt8(),
        # "geolocation/quality_flag_a4": pl.UInt8(),
        # "geolocation/quality_flag_a5": pl.UInt8(),
        # "geolocation/quality_flag_a6": pl.UInt8(),
        "geolocation/rh_a1": pl.List(pl.Int16()),
        "geolocation/rh_a2": pl.List(pl.Int16()),
        "geolocation/rh_a3": pl.List(pl.Int16()),
        "geolocation/rh_a4": pl.List(pl.Int16()),
        "geolocation/rh_a5": pl.List(pl.Int16()),
        "geolocation/rh_a6": pl.List(pl.Int16()),
        "geolocation/sensitivity_a1": pl.Float32(),
        "geolocation/sensitivity_a2": pl.Float32(),
        "geolocation/sensitivity_a3": pl.Float32(),
        "geolocation/sensitivity_a4": pl.Float32(),
        "geolocation/sensitivity_a5": pl.Float32(),
        "geolocation/sensitivity_a6": pl.Float32(),
        "geolocation/stale_return_flag": pl.UInt8(),
        "land_cover_data/landsat_treecover": pl.Float64(),
        "land_cover_data/landsat_water_persistence": pl.UInt8(),
        "land_cover_data/leaf_off_doy": pl.Int16(),
        "land_cover_data/leaf_off_flag": pl.UInt8(),
        "land_cover_data/leaf_on_cycle": pl.UInt8(),
        "land_cover_data/leaf_on_doy": pl.Int16(),
        "land_cover_data/modis_nonvegetated": pl.Float64(),
        "land_cover_data/modis_nonvegetated_sd": pl.Float64(),
        "land_cover_data/modis_treecover": pl.Float64(),
        "land_cover_data/modis_treecover_sd": pl.Float64(),
        "land_cover_data/pft_class": pl.UInt8(),
        "land_cover_data/region_class": pl.UInt8(),
        # "land_cover_data/urban_focal_window_size": pl.UInt8(),
        "land_cover_data/urban_proportion": pl.UInt8(),
        # "lat_highestreturn": pl.Float64(),
        "lat_lowestmode": pl.Float64(),
        # "latitude_bin0_error": pl.Float32(),
        # "lon_highestreturn": pl.Float64(),
        "lon_lowestmode": pl.Float64(),
        # "longitude_bin0_error": pl.Float32(),
        # "master_frac": pl.Float64(),
        # "master_int": pl.UInt32(),
        # "mean_sea_surface": pl.Float32(),
        "num_detectedmodes": pl.UInt8(),
        "quality_flag": pl.UInt8(),
        "rh": pl.List(pl.Float32()),
        # "rx_1gaussfit/ancillary/mpfit_max_func_evals": pl.Int64(),
        # "rx_1gaussfit/ancillary/mpfit_maxiters": pl.Int64(),
        # "rx_1gaussfit/ancillary/mpfit_tolerance": pl.Float64(),
        # "rx_1gaussfit/ancillary/rx_constraint_gamplitude_lower": pl.Float64(),
        # "rx_1gaussfit/ancillary/rx_constraint_gamplitude_upper": pl.Float64(),
        # "rx_1gaussfit/ancillary/rx_constraint_gloc_lower": pl.Float64(),
        # "rx_1gaussfit/ancillary/rx_constraint_gloc_upper": pl.Float64(),
        # "rx_1gaussfit/ancillary/rx_constraint_gwidth_lower": pl.Float64(),
        # "rx_1gaussfit/ancillary/rx_constraint_gwidth_upper": pl.Float64(),
        # "rx_1gaussfit/ancillary/rx_estimate_bias": pl.Int32(),
        # "rx_1gaussfit/ancillary/rx_mean_noise_level": pl.Float64(),
        # "rx_1gaussfit/ancillary/rx_smoothwidth": pl.Float64(),
        # "rx_1gaussfit/rx_gamplitude": pl.Float32(),
        # "rx_1gaussfit/rx_gamplitude_error": pl.Float32(),
        # "rx_1gaussfit/rx_gbias": pl.Float32(),
        # "rx_1gaussfit/rx_gbias_error": pl.Float32(),
        # "rx_1gaussfit/rx_gchisq": pl.Float32(),
        # "rx_1gaussfit/rx_gflag": pl.UInt8(),
        # "rx_1gaussfit/rx_giters": pl.UInt16(),
        # "rx_1gaussfit/rx_gloc": pl.Float32(),
        # "rx_1gaussfit/rx_gloc_error": pl.Float32(),
        # "rx_1gaussfit/rx_gwidth": pl.Float32(),
        # "rx_1gaussfit/rx_gwidth_error": pl.Float32(),
        # "rx_assess/ancillary/rx_ampbounds_ll": pl.Float64(),
        # "rx_assess/ancillary/rx_ampbounds_ul": pl.Float64(),
        # "rx_assess/ancillary/rx_clipamp": pl.Float64(),
        # "rx_assess/ancillary/rx_pulsethresh": pl.Float64(),
        # "rx_assess/ancillary/rx_ringthresh": pl.Float64(),
        # "rx_assess/ancillary/smoothing_width_locs": pl.Float64(),
        # "rx_assess/mean": pl.Float32(),
        # "rx_assess/mean_64kadjusted": pl.Float32(),
        # "rx_assess/ocean_calibration_shot_flag": pl.UInt8(),
        # "rx_assess/quality_flag": pl.UInt8(),
        # "rx_assess/rx_assess_flag": pl.UInt16(),
        # "rx_assess/rx_clipbin0": pl.UInt16(),
        # "rx_assess/rx_clipbin_count": pl.UInt16(),
        # "rx_assess/rx_energy": pl.Float32(),
        "rx_assess/rx_maxamp": pl.Float32(),
        # "rx_assess/rx_maxpeakloc": pl.UInt16(),
        "rx_assess/sd_corrected": pl.Float32(),
        # "rx_processing_a1/ancillary/amp_thresh": pl.Float64(),
        # "rx_processing_a1/ancillary/ampval_limit2": pl.Float64(),
        # "rx_processing_a1/ancillary/ampval_limit3": pl.Float64(),
        # "rx_processing_a1/ancillary/botlocdist_limit1": pl.Float64(),
        # "rx_processing_a1/ancillary/botlocdist_limit2": pl.Float64(),
        # "rx_processing_a1/ancillary/botlocdist_limit3": pl.Float64(),
        # "rx_processing_a1/ancillary/cumulative_energy_minimum": pl.Float64(),
        # "rx_processing_a1/ancillary/cumulative_energy_thresh": pl.Float64(),
        # "rx_processing_a1/ancillary/enable_select_mode": pl.Int32(),
        # "rx_processing_a1/ancillary/energy_thresh": pl.Float64(),
        # "rx_processing_a1/ancillary/preprocessor_threshold": pl.Float64(),
        # "rx_processing_a1/ancillary/pulse_sep_thresh": pl.Float64(),
        # "rx_processing_a1/ancillary/rx_back_threshold": pl.Float64(),
        # "rx_processing_a1/ancillary/rx_front_threshold": pl.Float64(),
        # "rx_processing_a1/ancillary/rx_max_mode_count": pl.Int64(),
        # "rx_processing_a1/ancillary/rx_searchsize": pl.Float64(),
        # "rx_processing_a1/ancillary/rx_sentinel_location": pl.Float64(),
        # "rx_processing_a1/ancillary/rx_smoothing_width_locs": pl.Float64(),
        # "rx_processing_a1/ancillary/rx_smoothing_width_zcross": pl.Float64(),
        # "rx_processing_a1/ancillary/rx_subbin_resolution": pl.Int64(),
        # "rx_processing_a1/ancillary/rx_use_fixed_thresholds": pl.Int32(),
        # "rx_processing_a1/back_threshold": pl.Float32(),
        # "rx_processing_a1/botloc": pl.Float32(),
        # "rx_processing_a1/botloc_amp": pl.Float32(),
        # "rx_processing_a1/energy_sm": pl.Float32(),
        # "rx_processing_a1/front_threshold": pl.Float32(),
        # "rx_processing_a1/lastmodeenergy": pl.Float32(),
        # "rx_processing_a1/mean": pl.Float32(),
        # "rx_processing_a1/mean_sm": pl.Float32(),
        # "rx_processing_a1/min_detection_energy": pl.Float32(),
        # "rx_processing_a1/min_detection_threshold": pl.Float32(),
        # "rx_processing_a1/peak": pl.Float32(),
        # "rx_processing_a1/pk_sm": pl.Float32(),
        "rx_processing_a1/rx_algrunflag": pl.UInt8(),
        # "rx_processing_a1/rx_cumulative": pl.List(pl.Float32()),
        # "rx_processing_a1/rx_iwaveamps": pl.List(pl.Float32()),
        # "rx_processing_a1/rx_modeamps": pl.List(pl.Float32()),
        # "rx_processing_a1/rx_modeenergytobotloc": pl.List(pl.Float32()),
        # "rx_processing_a1/rx_modelocalenergy": pl.List(pl.Float32()),
        # "rx_processing_a1/rx_modelocalenergyabovemean": pl.List(pl.Float32()),
        # "rx_processing_a1/rx_modelocalslope": pl.List(pl.Float32()),
        # "rx_processing_a1/rx_modelocs": pl.List(pl.Float32()),
        # "rx_processing_a1/rx_modewidths": pl.List(pl.Float32()),
        # "rx_processing_a1/rx_nummodes": pl.UInt8(),
        # "rx_processing_a1/sd_sm": pl.Float32(),
        # "rx_processing_a1/search_end": pl.Float32(),
        # "rx_processing_a1/search_start": pl.Float32(),
        # "rx_processing_a1/selected_mode": pl.UInt8(),
        # "rx_processing_a1/selected_mode_flag": pl.UInt8(),
        # "rx_processing_a1/smoothwidth": pl.Float32(),
        # "rx_processing_a1/smoothwidth_zcross": pl.Float32(),
        # "rx_processing_a1/stddev": pl.Float32(),
        "rx_processing_a1/toploc": pl.Float32(),
        # "rx_processing_a1/toploc_miss": pl.UInt8(),
        "rx_processing_a1/zcross": pl.Float32(),
        # "rx_processing_a1/zcross0": pl.Float32(),
        # "rx_processing_a1/zcross_amp": pl.Float32(),
        # "rx_processing_a1/zcross_localenergy": pl.Float32(),
        # "rx_processing_a2/ancillary/amp_thresh": pl.Float64(),
        # "rx_processing_a2/ancillary/ampval_limit2": pl.Float64(),
        # "rx_processing_a2/ancillary/ampval_limit3": pl.Float64(),
        # "rx_processing_a2/ancillary/botlocdist_limit1": pl.Float64(),
        # "rx_processing_a2/ancillary/botlocdist_limit2": pl.Float64(),
        # "rx_processing_a2/ancillary/botlocdist_limit3": pl.Float64(),
        # "rx_processing_a2/ancillary/cumulative_energy_minimum": pl.Float64(),
        # "rx_processing_a2/ancillary/cumulative_energy_thresh": pl.Float64(),
        # "rx_processing_a2/ancillary/enable_select_mode": pl.Int32(),
        # "rx_processing_a2/ancillary/energy_thresh": pl.Float64(),
        # "rx_processing_a2/ancillary/preprocessor_threshold": pl.Float64(),
        # "rx_processing_a2/ancillary/pulse_sep_thresh": pl.Float64(),
        # "rx_processing_a2/ancillary/rx_back_threshold": pl.Float64(),
        # "rx_processing_a2/ancillary/rx_front_threshold": pl.Float64(),
        # "rx_processing_a2/ancillary/rx_max_mode_count": pl.Int64(),
        # "rx_processing_a2/ancillary/rx_searchsize": pl.Float64(),
        # "rx_processing_a2/ancillary/rx_sentinel_location": pl.Float64(),
        # "rx_processing_a2/ancillary/rx_smoothing_width_locs": pl.Float64(),
        # "rx_processing_a2/ancillary/rx_smoothing_width_zcross": pl.Float64(),
        # "rx_processing_a2/ancillary/rx_subbin_resolution": pl.Int64(),
        # "rx_processing_a2/ancillary/rx_use_fixed_thresholds": pl.Int32(),
        # "rx_processing_a2/back_threshold": pl.Float32(),
        # "rx_processing_a2/botloc": pl.Float32(),
        # "rx_processing_a2/botloc_amp": pl.Float32(),
        # "rx_processing_a2/energy_sm": pl.Float32(),
        # "rx_processing_a2/front_threshold": pl.Float32(),
        # "rx_processing_a2/lastmodeenergy": pl.Float32(),
        # "rx_processing_a2/mean": pl.Float32(),
        # "rx_processing_a2/mean_sm": pl.Float32(),
        # "rx_processing_a2/min_detection_energy": pl.Float32(),
        # "rx_processing_a2/min_detection_threshold": pl.Float32(),
        # "rx_processing_a2/peak": pl.Float32(),
        # "rx_processing_a2/pk_sm": pl.Float32(),
        "rx_processing_a2/rx_algrunflag": pl.UInt8(),
        # "rx_processing_a2/rx_cumulative": pl.List(pl.Float32()),
        # "rx_processing_a2/rx_iwaveamps": pl.List(pl.Float32()),
        # "rx_processing_a2/rx_modeamps": pl.List(pl.Float32()),
        # "rx_processing_a2/rx_modeenergytobotloc": pl.List(pl.Float32()),
        # "rx_processing_a2/rx_modelocalenergy": pl.List(pl.Float32()),
        # "rx_processing_a2/rx_modelocalenergyabovemean": pl.List(pl.Float32()),
        # "rx_processing_a2/rx_modelocalslope": pl.List(pl.Float32()),
        # "rx_processing_a2/rx_modelocs": pl.List(pl.Float32()),
        # "rx_processing_a2/rx_modewidths": pl.List(pl.Float32()),
        # "rx_processing_a2/rx_nummodes": pl.UInt8(),
        # "rx_processing_a2/sd_sm": pl.Float32(),
        # "rx_processing_a2/search_end": pl.Float32(),
        # "rx_processing_a2/search_start": pl.Float32(),
        # "rx_processing_a2/selected_mode": pl.UInt8(),
        # "rx_processing_a2/selected_mode_flag": pl.UInt8(),
        # "rx_processing_a2/smoothwidth": pl.Float32(),
        # "rx_processing_a2/smoothwidth_zcross": pl.Float32(),
        # "rx_processing_a2/stddev": pl.Float32(),
        "rx_processing_a2/toploc": pl.Float32(),
        # "rx_processing_a2/toploc_miss": pl.UInt8(),
        "rx_processing_a2/zcross": pl.Float32(),
        # "rx_processing_a2/zcross0": pl.Float32(),
        # "rx_processing_a2/zcross_amp": pl.Float32(),
        # "rx_processing_a2/zcross_localenergy": pl.Float32(),
        # "rx_processing_a3/ancillary/amp_thresh": pl.Float64(),
        # "rx_processing_a3/ancillary/ampval_limit2": pl.Float64(),
        # "rx_processing_a3/ancillary/ampval_limit3": pl.Float64(),
        # "rx_processing_a3/ancillary/botlocdist_limit1": pl.Float64(),
        # "rx_processing_a3/ancillary/botlocdist_limit2": pl.Float64(),
        # "rx_processing_a3/ancillary/botlocdist_limit3": pl.Float64(),
        # "rx_processing_a3/ancillary/cumulative_energy_minimum": pl.Float64(),
        # "rx_processing_a3/ancillary/cumulative_energy_thresh": pl.Float64(),
        # "rx_processing_a3/ancillary/enable_select_mode": pl.Int32(),
        # "rx_processing_a3/ancillary/energy_thresh": pl.Float64(),
        # "rx_processing_a3/ancillary/preprocessor_threshold": pl.Float64(),
        # "rx_processing_a3/ancillary/pulse_sep_thresh": pl.Float64(),
        # "rx_processing_a3/ancillary/rx_back_threshold": pl.Float64(),
        # "rx_processing_a3/ancillary/rx_front_threshold": pl.Float64(),
        # "rx_processing_a3/ancillary/rx_max_mode_count": pl.Int64(),
        # "rx_processing_a3/ancillary/rx_searchsize": pl.Float64(),
        # "rx_processing_a3/ancillary/rx_sentinel_location": pl.Float64(),
        # "rx_processing_a3/ancillary/rx_smoothing_width_locs": pl.Float64(),
        # "rx_processing_a3/ancillary/rx_smoothing_width_zcross": pl.Float64(),
        # "rx_processing_a3/ancillary/rx_subbin_resolution": pl.Int64(),
        # "rx_processing_a3/ancillary/rx_use_fixed_thresholds": pl.Int32(),
        # "rx_processing_a3/back_threshold": pl.Float32(),
        # "rx_processing_a3/botloc": pl.Float32(),
        # "rx_processing_a3/botloc_amp": pl.Float32(),
        # "rx_processing_a3/energy_sm": pl.Float32(),
        # "rx_processing_a3/front_threshold": pl.Float32(),
        # "rx_processing_a3/lastmodeenergy": pl.Float32(),
        # "rx_processing_a3/mean": pl.Float32(),
        # "rx_processing_a3/mean_sm": pl.Float32(),
        # "rx_processing_a3/min_detection_energy": pl.Float32(),
        # "rx_processing_a3/min_detection_threshold": pl.Float32(),
        # "rx_processing_a3/peak": pl.Float32(),
        # "rx_processing_a3/pk_sm": pl.Float32(),
        "rx_processing_a3/rx_algrunflag": pl.UInt8(),
        # "rx_processing_a3/rx_cumulative": pl.List(pl.Float32()),
        # "rx_processing_a3/rx_iwaveamps": pl.List(pl.Float32()),
        # "rx_processing_a3/rx_modeamps": pl.List(pl.Float32()),
        # "rx_processing_a3/rx_modeenergytobotloc": pl.List(pl.Float32()),
        # "rx_processing_a3/rx_modelocalenergy": pl.List(pl.Float32()),
        # "rx_processing_a3/rx_modelocalenergyabovemean": pl.List(pl.Float32()),
        # "rx_processing_a3/rx_modelocalslope": pl.List(pl.Float32()),
        # "rx_processing_a3/rx_modelocs": pl.List(pl.Float32()),
        # "rx_processing_a3/rx_modewidths": pl.List(pl.Float32()),
        # "rx_processing_a3/rx_nummodes": pl.UInt8(),
        # "rx_processing_a3/sd_sm": pl.Float32(),
        # "rx_processing_a3/search_end": pl.Float32(),
        # "rx_processing_a3/search_start": pl.Float32(),
        # "rx_processing_a3/selected_mode": pl.UInt8(),
        # "rx_processing_a3/selected_mode_flag": pl.UInt8(),
        # "rx_processing_a3/smoothwidth": pl.Float32(),
        # "rx_processing_a3/smoothwidth_zcross": pl.Float32(),
        # "rx_processing_a3/stddev": pl.Float32(),
        "rx_processing_a3/toploc": pl.Float32(),
        # "rx_processing_a3/toploc_miss": pl.UInt8(),
        "rx_processing_a3/zcross": pl.Float32(),
        # "rx_processing_a3/zcross0": pl.Float32(),
        # "rx_processing_a3/zcross_amp": pl.Float32(),
        # "rx_processing_a3/zcross_localenergy": pl.Float32(),
        # "rx_processing_a4/ancillary/amp_thresh": pl.Float64(),
        # "rx_processing_a4/ancillary/ampval_limit2": pl.Float64(),
        # "rx_processing_a4/ancillary/ampval_limit3": pl.Float64(),
        # "rx_processing_a4/ancillary/botlocdist_limit1": pl.Float64(),
        # "rx_processing_a4/ancillary/botlocdist_limit2": pl.Float64(),
        # "rx_processing_a4/ancillary/botlocdist_limit3": pl.Float64(),
        # "rx_processing_a4/ancillary/cumulative_energy_minimum": pl.Float64(),
        # "rx_processing_a4/ancillary/cumulative_energy_thresh": pl.Float64(),
        # "rx_processing_a4/ancillary/enable_select_mode": pl.Int32(),
        # "rx_processing_a4/ancillary/energy_thresh": pl.Float64(),
        # "rx_processing_a4/ancillary/preprocessor_threshold": pl.Float64(),
        # "rx_processing_a4/ancillary/pulse_sep_thresh": pl.Float64(),
        # "rx_processing_a4/ancillary/rx_back_threshold": pl.Float64(),
        # "rx_processing_a4/ancillary/rx_front_threshold": pl.Float64(),
        # "rx_processing_a4/ancillary/rx_max_mode_count": pl.Int64(),
        # "rx_processing_a4/ancillary/rx_searchsize": pl.Float64(),
        # "rx_processing_a4/ancillary/rx_sentinel_location": pl.Float64(),
        # "rx_processing_a4/ancillary/rx_smoothing_width_locs": pl.Float64(),
        # "rx_processing_a4/ancillary/rx_smoothing_width_zcross": pl.Float64(),
        # "rx_processing_a4/ancillary/rx_subbin_resolution": pl.Int64(),
        # "rx_processing_a4/ancillary/rx_use_fixed_thresholds": pl.Int32(),
        # "rx_processing_a4/back_threshold": pl.Float32(),
        # "rx_processing_a4/botloc": pl.Float32(),
        # "rx_processing_a4/botloc_amp": pl.Float32(),
        # "rx_processing_a4/energy_sm": pl.Float32(),
        # "rx_processing_a4/front_threshold": pl.Float32(),
        # "rx_processing_a4/lastmodeenergy": pl.Float32(),
        # "rx_processing_a4/mean": pl.Float32(),
        # "rx_processing_a4/mean_sm": pl.Float32(),
        # "rx_processing_a4/min_detection_energy": pl.Float32(),
        # "rx_processing_a4/min_detection_threshold": pl.Float32(),
        # "rx_processing_a4/peak": pl.Float32(),
        # "rx_processing_a4/pk_sm": pl.Float32(),
        "rx_processing_a4/rx_algrunflag": pl.UInt8(),
        # "rx_processing_a4/rx_cumulative": pl.List(pl.Float32()),
        # "rx_processing_a4/rx_iwaveamps": pl.List(pl.Float32()),
        # "rx_processing_a4/rx_modeamps": pl.List(pl.Float32()),
        # "rx_processing_a4/rx_modeenergytobotloc": pl.List(pl.Float32()),
        # "rx_processing_a4/rx_modelocalenergy": pl.List(pl.Float32()),
        # "rx_processing_a4/rx_modelocalenergyabovemean": pl.List(pl.Float32()),
        # "rx_processing_a4/rx_modelocalslope": pl.List(pl.Float32()),
        # "rx_processing_a4/rx_modelocs": pl.List(pl.Float32()),
        # "rx_processing_a4/rx_modewidths": pl.List(pl.Float32()),
        # "rx_processing_a4/rx_nummodes": pl.UInt8(),
        # "rx_processing_a4/sd_sm": pl.Float32(),
        # "rx_processing_a4/search_end": pl.Float32(),
        # "rx_processing_a4/search_start": pl.Float32(),
        # "rx_processing_a4/selected_mode": pl.UInt8(),
        # "rx_processing_a4/selected_mode_flag": pl.UInt8(),
        # "rx_processing_a4/smoothwidth": pl.Float32(),
        # "rx_processing_a4/smoothwidth_zcross": pl.Float32(),
        # "rx_processing_a4/stddev": pl.Float32(),
        "rx_processing_a4/toploc": pl.Float32(),
        # "rx_processing_a4/toploc_miss": pl.UInt8(),
        "rx_processing_a4/zcross": pl.Float32(),
        # "rx_processing_a4/zcross0": pl.Float32(),
        # "rx_processing_a4/zcross_amp": pl.Float32(),
        # "rx_processing_a4/zcross_localenergy": pl.Float32(),
        # "rx_processing_a5/ancillary/amp_thresh": pl.Float64(),
        # "rx_processing_a5/ancillary/ampval_limit2": pl.Float64(),
        # "rx_processing_a5/ancillary/ampval_limit3": pl.Float64(),
        # "rx_processing_a5/ancillary/botlocdist_limit1": pl.Float64(),
        # "rx_processing_a5/ancillary/botlocdist_limit2": pl.Float64(),
        # "rx_processing_a5/ancillary/botlocdist_limit3": pl.Float64(),
        # "rx_processing_a5/ancillary/cumulative_energy_minimum": pl.Float64(),
        # "rx_processing_a5/ancillary/cumulative_energy_thresh": pl.Float64(),
        # "rx_processing_a5/ancillary/enable_select_mode": pl.Int32(),
        # "rx_processing_a5/ancillary/energy_thresh": pl.Float64(),
        # "rx_processing_a5/ancillary/preprocessor_threshold": pl.Float64(),
        # "rx_processing_a5/ancillary/pulse_sep_thresh": pl.Float64(),
        # "rx_processing_a5/ancillary/rx_back_threshold": pl.Float64(),
        # "rx_processing_a5/ancillary/rx_front_threshold": pl.Float64(),
        # "rx_processing_a5/ancillary/rx_max_mode_count": pl.Int64(),
        # "rx_processing_a5/ancillary/rx_searchsize": pl.Float64(),
        # "rx_processing_a5/ancillary/rx_sentinel_location": pl.Float64(),
        # "rx_processing_a5/ancillary/rx_smoothing_width_locs": pl.Float64(),
        # "rx_processing_a5/ancillary/rx_smoothing_width_zcross": pl.Float64(),
        # "rx_processing_a5/ancillary/rx_subbin_resolution": pl.Int64(),
        # "rx_processing_a5/ancillary/rx_use_fixed_thresholds": pl.Int32(),
        # "rx_processing_a5/back_threshold": pl.Float32(),
        # "rx_processing_a5/botloc": pl.Float32(),
        # "rx_processing_a5/botloc_amp": pl.Float32(),
        # "rx_processing_a5/energy_sm": pl.Float32(),
        # "rx_processing_a5/front_threshold": pl.Float32(),
        # "rx_processing_a5/lastmodeenergy": pl.Float32(),
        # "rx_processing_a5/mean": pl.Float32(),
        # "rx_processing_a5/mean_sm": pl.Float32(),
        # "rx_processing_a5/min_detection_energy": pl.Float32(),
        # "rx_processing_a5/min_detection_threshold": pl.Float32(),
        # "rx_processing_a5/peak": pl.Float32(),
        # "rx_processing_a5/pk_sm": pl.Float32(),
        "rx_processing_a5/rx_algrunflag": pl.UInt8(),
        # "rx_processing_a5/rx_cumulative": pl.List(pl.Float32()),
        # "rx_processing_a5/rx_iwaveamps": pl.List(pl.Float32()),
        # "rx_processing_a5/rx_modeamps": pl.List(pl.Float32()),
        # "rx_processing_a5/rx_modeenergytobotloc": pl.List(pl.Float32()),
        # "rx_processing_a5/rx_modelocalenergy": pl.List(pl.Float32()),
        # "rx_processing_a5/rx_modelocalenergyabovemean": pl.List(pl.Float32()),
        # "rx_processing_a5/rx_modelocalslope": pl.List(pl.Float32()),
        # "rx_processing_a5/rx_modelocs": pl.List(pl.Float32()),
        # "rx_processing_a5/rx_modewidths": pl.List(pl.Float32()),
        # "rx_processing_a5/rx_nummodes": pl.UInt8(),
        # "rx_processing_a5/sd_sm": pl.Float32(),
        # "rx_processing_a5/search_end": pl.Float32(),
        # "rx_processing_a5/search_start": pl.Float32(),
        # "rx_processing_a5/selected_mode": pl.UInt8(),
        # "rx_processing_a5/selected_mode_flag": pl.UInt8(),
        # "rx_processing_a5/smoothwidth": pl.Float32(),
        # "rx_processing_a5/smoothwidth_zcross": pl.Float32(),
        # "rx_processing_a5/stddev": pl.Float32(),
        "rx_processing_a5/toploc": pl.Float32(),
        # "rx_processing_a5/toploc_miss": pl.UInt8(),
        "rx_processing_a5/zcross": pl.Float32(),
        # "rx_processing_a5/zcross0": pl.Float32(),
        # "rx_processing_a5/zcross_amp": pl.Float32(),
        # "rx_processing_a5/zcross_localenergy": pl.Float32(),
        # "rx_processing_a6/ancillary/amp_thresh": pl.Float64(),
        # "rx_processing_a6/ancillary/ampval_limit2": pl.Float64(),
        # "rx_processing_a6/ancillary/ampval_limit3": pl.Float64(),
        # "rx_processing_a6/ancillary/botlocdist_limit1": pl.Float64(),
        # "rx_processing_a6/ancillary/botlocdist_limit2": pl.Float64(),
        # "rx_processing_a6/ancillary/botlocdist_limit3": pl.Float64(),
        # "rx_processing_a6/ancillary/cumulative_energy_minimum": pl.Float64(),
        # "rx_processing_a6/ancillary/cumulative_energy_thresh": pl.Float64(),
        # "rx_processing_a6/ancillary/enable_select_mode": pl.Int32(),
        # "rx_processing_a6/ancillary/energy_thresh": pl.Float64(),
        # "rx_processing_a6/ancillary/preprocessor_threshold": pl.Float64(),
        # "rx_processing_a6/ancillary/pulse_sep_thresh": pl.Float64(),
        # "rx_processing_a6/ancillary/rx_back_threshold": pl.Float64(),
        # "rx_processing_a6/ancillary/rx_front_threshold": pl.Float64(),
        # "rx_processing_a6/ancillary/rx_max_mode_count": pl.Int64(),
        # "rx_processing_a6/ancillary/rx_searchsize": pl.Float64(),
        # "rx_processing_a6/ancillary/rx_sentinel_location": pl.Float64(),
        # "rx_processing_a6/ancillary/rx_smoothing_width_locs": pl.Float64(),
        # "rx_processing_a6/ancillary/rx_smoothing_width_zcross": pl.Float64(),
        # "rx_processing_a6/ancillary/rx_subbin_resolution": pl.Int64(),
        # "rx_processing_a6/ancillary/rx_use_fixed_thresholds": pl.Int32(),
        # "rx_processing_a6/back_threshold": pl.Float32(),
        # "rx_processing_a6/botloc": pl.Float32(),
        # "rx_processing_a6/botloc_amp": pl.Float32(),
        # "rx_processing_a6/energy_sm": pl.Float32(),
        # "rx_processing_a6/front_threshold": pl.Float32(),
        # "rx_processing_a6/lastmodeenergy": pl.Float32(),
        # "rx_processing_a6/mean": pl.Float32(),
        # "rx_processing_a6/mean_sm": pl.Float32(),
        # "rx_processing_a6/min_detection_energy": pl.Float32(),
        # "rx_processing_a6/min_detection_threshold": pl.Float32(),
        # "rx_processing_a6/peak": pl.Float32(),
        # "rx_processing_a6/pk_sm": pl.Float32(),
        "rx_processing_a6/rx_algrunflag": pl.UInt8(),
        # "rx_processing_a6/rx_cumulative": pl.List(pl.Float32()),
        # "rx_processing_a6/rx_iwaveamps": pl.List(pl.Float32()),
        # "rx_processing_a6/rx_modeamps": pl.List(pl.Float32()),
        # "rx_processing_a6/rx_modeenergytobotloc": pl.List(pl.Float32()),
        # "rx_processing_a6/rx_modelocalenergy": pl.List(pl.Float32()),
        # "rx_processing_a6/rx_modelocalenergyabovemean": pl.List(pl.Float32()),
        # "rx_processing_a6/rx_modelocalslope": pl.List(pl.Float32()),
        # "rx_processing_a6/rx_modelocs": pl.List(pl.Float32()),
        # "rx_processing_a6/rx_modewidths": pl.List(pl.Float32()),
        # "rx_processing_a6/rx_nummodes": pl.UInt8(),
        # "rx_processing_a6/sd_sm": pl.Float32(),
        # "rx_processing_a6/search_end": pl.Float32(),
        # "rx_processing_a6/search_start": pl.Float32(),
        # "rx_processing_a6/selected_mode": pl.UInt8(),
        # "rx_processing_a6/selected_mode_flag": pl.UInt8(),
        # "rx_processing_a6/smoothwidth": pl.Float32(),
        # "rx_processing_a6/smoothwidth_zcross": pl.Float32(),
        # "rx_processing_a6/stddev": pl.Float32(),
        "rx_processing_a6/toploc": pl.Float32(),
        # "rx_processing_a6/toploc_miss": pl.UInt8(),
        "rx_processing_a6/zcross": pl.Float32(),
        # "rx_processing_a6/zcross0": pl.Float32(),
        # "rx_processing_a6/zcross_amp": pl.Float32(),
        # "rx_processing_a6/zcross_localenergy": pl.Float32(),
        "selected_algorithm": pl.UInt8(),
        "selected_mode": pl.UInt8(),
        "selected_mode_flag": pl.UInt8(),
        "sensitivity": pl.Float32(),
        "shot_number": pl.UInt64(),
        "solar_azimuth": pl.Float32(),
        "solar_elevation": pl.Float32(),
        "surface_flag": pl.UInt8(),
    },
)
