import typing as t

import polars as pl

# The full schema was produced via gedi_geoparquet.polars_._infer_schema.
# Although we're selecting only a subset of columns, we're leaving the unused
# columns in comments so we have a full reference of what's available.

# NOTE: One field was manually modified: geolocation/degrade_flag
# It was changed from pl.Int8 to pl.UInt8 because it is pl.UInt8 in all of the
# other collections.  This may be an oversight in the process that produces the
# L2B data files.
SCHEMA: t.Final = pl.Schema(
    {
        # "algorithmrun_flag": pl.UInt8(),
        "ancillary/dz": pl.Float64(),
        # "ancillary/l2a_alg_count": pl.Int64(),
        # "ancillary/maxheight_cuttoff": pl.Float64(),
        # "ancillary/rg_eg_constraint_center_buffer": pl.Int32(),
        # "ancillary/rg_eg_mpfit_max_func_evals": pl.UInt16(),
        # "ancillary/rg_eg_mpfit_maxiters": pl.UInt16(),
        # "ancillary/rg_eg_mpfit_tolerance": pl.Float64(),
        # "ancillary/signal_search_buff": pl.Float64(),
        # "ancillary/tx_noise_stddev_multiplier": pl.Float64(),
        # "beam": pl.UInt16(),
        # "channel": pl.UInt8(),
        "cover": pl.Float32(),
        "cover_z": pl.List(pl.Float32()),
        "delta_time": pl.Float64(),
        "fhd_normal": pl.Float32(),
        "geolocation/degrade_flag": pl.UInt8(),
        # "geolocation/delta_time": pl.Float64(),
        "geolocation/digital_elevation_model": pl.Float32(),
        # "geolocation/elev_highestreturn": pl.Float32(),
        "geolocation/elev_lowestmode": pl.Float32(),
        # "geolocation/elevation_bin0": pl.Float64(),
        # "geolocation/elevation_bin0_error": pl.Float32(),
        # "geolocation/elevation_lastbin": pl.Float64(),
        # "geolocation/elevation_lastbin_error": pl.Float32(),
        # "geolocation/height_bin0": pl.Float32(),
        # "geolocation/height_lastbin": pl.Float32(),
        # "geolocation/lat_highestreturn": pl.Float64(),
        "geolocation/lat_lowestmode": pl.Float64(),
        # "geolocation/latitude_bin0": pl.Float64(),
        # "geolocation/latitude_bin0_error": pl.Float32(),
        # "geolocation/latitude_lastbin": pl.Float64(),
        # "geolocation/latitude_lastbin_error": pl.Float32(),
        # "geolocation/local_beam_azimuth": pl.Float32(),
        # "geolocation/local_beam_elevation": pl.Float32(),
        # "geolocation/lon_highestreturn": pl.Float64(),
        "geolocation/lon_lowestmode": pl.Float64(),
        # "geolocation/longitude_bin0": pl.Float64(),
        # "geolocation/longitude_bin0_error": pl.Float32(),
        # "geolocation/longitude_lastbin": pl.Float64(),
        # "geolocation/longitude_lastbin_error": pl.Float32(),
        # "geolocation/shot_number": pl.UInt64(),
        "geolocation/solar_azimuth": pl.Float32(),
        "geolocation/solar_elevation": pl.Float32(),
        "l2a_quality_flag": pl.UInt8(),
        "l2b_quality_flag": pl.UInt8(),
        "land_cover_data/landsat_treecover": pl.Float64(),
        "land_cover_data/landsat_water_persistence": pl.UInt8(),
        "land_cover_data/leaf_off_doy": pl.Int16(),
        "land_cover_data/leaf_off_flag": pl.UInt8(),
        "land_cover_data/leaf_on_cycle": pl.UInt8(),
        "land_cover_data/leaf_on_doy": pl.Int16(),
        "land_cover_data/modis_nonvegetated": pl.Float64(),
        "land_cover_data/modis_nonvegetated_sd": pl.Float64(),
        "land_cover_data/modis_treecover": pl.Float64(),
        "land_cover_data/modis_treecover_sd": pl.Float64(),
        "land_cover_data/pft_class": pl.UInt8(),
        "land_cover_data/region_class": pl.UInt8(),
        # "land_cover_data/urban_focal_window_size": pl.UInt8(),
        "land_cover_data/urban_proportion": pl.UInt8(),
        # "master_frac": pl.Float64(),
        # "master_int": pl.UInt32(),
        "num_detectedmodes": pl.UInt8(),
        "omega": pl.Float32(),
        "pai": pl.Float32(),
        "pai_z": pl.List(pl.Float32()),
        "pavd_z": pl.List(pl.Float32()),
        "pgap_theta": pl.Float32(),
        "pgap_theta_error": pl.Float32(),
        #
        # pgap_theta_z is over 25 times longer than the other datasets, so we
        # cannot include it in the schema.  It has no coordinates attribute
        # either, so it is completely unclear how these values relate to
        # anything.  We must exclude this from the schema, otherwise we get a
        # Polars ComputeError/ShapeError.
        #
        # "pgap_theta_z": pl.Float32(),
        #
        "rg": pl.Float32(),
        "rh100": pl.Int16(),
        "rhog": pl.Float32(),
        "rhog_error": pl.Float32(),
        "rhov": pl.Float32(),
        "rhov_error": pl.Float32(),
        "rossg": pl.Float32(),
        "rv": pl.Float32(),
        # "rx_processing/algorithmrun_flag_a1": pl.UInt8(),
        # "rx_processing/algorithmrun_flag_a2": pl.UInt8(),
        # "rx_processing/algorithmrun_flag_a3": pl.UInt8(),
        # "rx_processing/algorithmrun_flag_a4": pl.UInt8(),
        # "rx_processing/algorithmrun_flag_a5": pl.UInt8(),
        # "rx_processing/algorithmrun_flag_a6": pl.UInt8(),
        # "rx_processing/pgap_theta_a1": pl.Float32(),
        # "rx_processing/pgap_theta_a2": pl.Float32(),
        # "rx_processing/pgap_theta_a3": pl.Float32(),
        # "rx_processing/pgap_theta_a4": pl.Float32(),
        # "rx_processing/pgap_theta_a5": pl.Float32(),
        # "rx_processing/pgap_theta_a6": pl.Float32(),
        # "rx_processing/pgap_theta_error_a1": pl.Float32(),
        # "rx_processing/pgap_theta_error_a2": pl.Float32(),
        # "rx_processing/pgap_theta_error_a3": pl.Float32(),
        # "rx_processing/pgap_theta_error_a4": pl.Float32(),
        # "rx_processing/pgap_theta_error_a5": pl.Float32(),
        # "rx_processing/pgap_theta_error_a6": pl.Float32(),
        # "rx_processing/rg_a1": pl.Float32(),
        # "rx_processing/rg_a2": pl.Float32(),
        # "rx_processing/rg_a3": pl.Float32(),
        # "rx_processing/rg_a4": pl.Float32(),
        # "rx_processing/rg_a5": pl.Float32(),
        # "rx_processing/rg_a6": pl.Float32(),
        # "rx_processing/rg_eg_amplitude_a1": pl.Float32(),
        # "rx_processing/rg_eg_amplitude_a2": pl.Float32(),
        # "rx_processing/rg_eg_amplitude_a3": pl.Float32(),
        # "rx_processing/rg_eg_amplitude_a4": pl.Float32(),
        # "rx_processing/rg_eg_amplitude_a5": pl.Float32(),
        # "rx_processing/rg_eg_amplitude_a6": pl.Float32(),
        # "rx_processing/rg_eg_amplitude_error_a1": pl.Float32(),
        # "rx_processing/rg_eg_amplitude_error_a2": pl.Float32(),
        # "rx_processing/rg_eg_amplitude_error_a3": pl.Float32(),
        # "rx_processing/rg_eg_amplitude_error_a4": pl.Float32(),
        # "rx_processing/rg_eg_amplitude_error_a5": pl.Float32(),
        # "rx_processing/rg_eg_amplitude_error_a6": pl.Float32(),
        # "rx_processing/rg_eg_center_a1": pl.Float32(),
        # "rx_processing/rg_eg_center_a2": pl.Float32(),
        # "rx_processing/rg_eg_center_a3": pl.Float32(),
        # "rx_processing/rg_eg_center_a4": pl.Float32(),
        # "rx_processing/rg_eg_center_a5": pl.Float32(),
        # "rx_processing/rg_eg_center_a6": pl.Float32(),
        # "rx_processing/rg_eg_center_error_a1": pl.Float32(),
        # "rx_processing/rg_eg_center_error_a2": pl.Float32(),
        # "rx_processing/rg_eg_center_error_a3": pl.Float32(),
        # "rx_processing/rg_eg_center_error_a4": pl.Float32(),
        # "rx_processing/rg_eg_center_error_a5": pl.Float32(),
        # "rx_processing/rg_eg_center_error_a6": pl.Float32(),
        # "rx_processing/rg_eg_chisq_a1": pl.Float32(),
        # "rx_processing/rg_eg_chisq_a2": pl.Float32(),
        # "rx_processing/rg_eg_chisq_a3": pl.Float32(),
        # "rx_processing/rg_eg_chisq_a4": pl.Float32(),
        # "rx_processing/rg_eg_chisq_a5": pl.Float32(),
        # "rx_processing/rg_eg_chisq_a6": pl.Float32(),
        # "rx_processing/rg_eg_flag_a1": pl.Int8(),
        # "rx_processing/rg_eg_flag_a2": pl.Int8(),
        # "rx_processing/rg_eg_flag_a3": pl.Int8(),
        # "rx_processing/rg_eg_flag_a4": pl.Int8(),
        # "rx_processing/rg_eg_flag_a5": pl.Int8(),
        # "rx_processing/rg_eg_flag_a6": pl.Int8(),
        # "rx_processing/rg_eg_gamma_a1": pl.Float32(),
        # "rx_processing/rg_eg_gamma_a2": pl.Float32(),
        # "rx_processing/rg_eg_gamma_a3": pl.Float32(),
        # "rx_processing/rg_eg_gamma_a4": pl.Float32(),
        # "rx_processing/rg_eg_gamma_a5": pl.Float32(),
        # "rx_processing/rg_eg_gamma_a6": pl.Float32(),
        # "rx_processing/rg_eg_gamma_error_a1": pl.Float32(),
        # "rx_processing/rg_eg_gamma_error_a2": pl.Float32(),
        # "rx_processing/rg_eg_gamma_error_a3": pl.Float32(),
        # "rx_processing/rg_eg_gamma_error_a4": pl.Float32(),
        # "rx_processing/rg_eg_gamma_error_a5": pl.Float32(),
        # "rx_processing/rg_eg_gamma_error_a6": pl.Float32(),
        # "rx_processing/rg_eg_niter_a1": pl.UInt8(),
        # "rx_processing/rg_eg_niter_a2": pl.UInt8(),
        # "rx_processing/rg_eg_niter_a3": pl.UInt8(),
        # "rx_processing/rg_eg_niter_a4": pl.UInt8(),
        # "rx_processing/rg_eg_niter_a5": pl.UInt8(),
        # "rx_processing/rg_eg_niter_a6": pl.UInt8(),
        # "rx_processing/rg_eg_sigma_a1": pl.Float32(),
        # "rx_processing/rg_eg_sigma_a2": pl.Float32(),
        # "rx_processing/rg_eg_sigma_a3": pl.Float32(),
        # "rx_processing/rg_eg_sigma_a4": pl.Float32(),
        # "rx_processing/rg_eg_sigma_a5": pl.Float32(),
        # "rx_processing/rg_eg_sigma_a6": pl.Float32(),
        # "rx_processing/rg_eg_sigma_error_a1": pl.Float32(),
        # "rx_processing/rg_eg_sigma_error_a2": pl.Float32(),
        # "rx_processing/rg_eg_sigma_error_a3": pl.Float32(),
        # "rx_processing/rg_eg_sigma_error_a4": pl.Float32(),
        # "rx_processing/rg_eg_sigma_error_a5": pl.Float32(),
        # "rx_processing/rg_eg_sigma_error_a6": pl.Float32(),
        # "rx_processing/rg_error_a1": pl.Float32(),
        # "rx_processing/rg_error_a2": pl.Float32(),
        # "rx_processing/rg_error_a3": pl.Float32(),
        # "rx_processing/rg_error_a4": pl.Float32(),
        # "rx_processing/rg_error_a5": pl.Float32(),
        # "rx_processing/rg_error_a6": pl.Float32(),
        # "rx_processing/rv_a1": pl.Float32(),
        # "rx_processing/rv_a2": pl.Float32(),
        # "rx_processing/rv_a3": pl.Float32(),
        # "rx_processing/rv_a4": pl.Float32(),
        # "rx_processing/rv_a5": pl.Float32(),
        # "rx_processing/rv_a6": pl.Float32(),
        # "rx_processing/rx_energy_a1": pl.Float32(),
        # "rx_processing/rx_energy_a2": pl.Float32(),
        # "rx_processing/rx_energy_a3": pl.Float32(),
        # "rx_processing/rx_energy_a4": pl.Float32(),
        # "rx_processing/rx_energy_a5": pl.Float32(),
        # "rx_processing/rx_energy_a6": pl.Float32(),
        # "rx_processing/shot_number": pl.UInt64(),
        "rx_range_highestreturn": pl.Float64(),
        # "rx_sample_count": pl.Int64(),
        # "rx_sample_start_index": pl.Int64(),
        "selected_l2a_algorithm": pl.UInt8(),
        "selected_mode": pl.UInt8(),
        "selected_mode_flag": pl.UInt8(),
        "selected_rg_algorithm": pl.UInt8(),
        "sensitivity": pl.Float32(),
        "shot_number": pl.UInt64(),
        "stale_return_flag": pl.UInt8(),
        "surface_flag": pl.UInt8(),
    },
)
