import typing as t

import polars as pl

# The full schema was produced via gedi_geoparquet.polars_._infer_schema.
# Although we're selecting only a subset of columns, we're leaving the unused
# columns in comments so we have a full reference of what's available.
SCHEMA: t.Final = pl.Schema(
    {
        "algorithm_run_flag": pl.UInt8(),
        # "beam": pl.UInt16(),
        # "channel": pl.UInt8(),
        "degrade_flag": pl.UInt8(),
        "delta_time": pl.Float64(),
        "elev_lowestmode": pl.Float32(),
        "elev_outlier_flag": pl.UInt8(),
        "fhd_normal": pl.Float64(),
        # "geolocation/elev_lowestmode_a1": pl.Float32(),
        # "geolocation/elev_lowestmode_a10": pl.Float32(),
        # "geolocation/elev_lowestmode_a2": pl.Float32(),
        # "geolocation/elev_lowestmode_a3": pl.Float32(),
        # "geolocation/elev_lowestmode_a4": pl.Float32(),
        # "geolocation/elev_lowestmode_a5": pl.Float32(),
        # "geolocation/elev_lowestmode_a6": pl.Float32(),
        # "geolocation/lat_lowestmode_a1": pl.Float64(),
        # "geolocation/lat_lowestmode_a10": pl.Float64(),
        # "geolocation/lat_lowestmode_a2": pl.Float64(),
        # "geolocation/lat_lowestmode_a3": pl.Float64(),
        # "geolocation/lat_lowestmode_a4": pl.Float64(),
        # "geolocation/lat_lowestmode_a5": pl.Float64(),
        # "geolocation/lat_lowestmode_a6": pl.Float64(),
        # "geolocation/lon_lowestmode_a1": pl.Float64(),
        # "geolocation/lon_lowestmode_a10": pl.Float64(),
        # "geolocation/lon_lowestmode_a2": pl.Float64(),
        # "geolocation/lon_lowestmode_a3": pl.Float64(),
        # "geolocation/lon_lowestmode_a4": pl.Float64(),
        # "geolocation/lon_lowestmode_a5": pl.Float64(),
        # "geolocation/lon_lowestmode_a6": pl.Float64(),
        "geolocation/sensitivity_a1": pl.Float32(),
        # "geolocation/sensitivity_a10": pl.Float32(),
        "geolocation/sensitivity_a2": pl.Float32(),
        # "geolocation/sensitivity_a3": pl.Float32(),
        # "geolocation/sensitivity_a4": pl.Float32(),
        # "geolocation/sensitivity_a5": pl.Float32(),
        # "geolocation/sensitivity_a6": pl.Float32(),
        # "geolocation/shot_number": pl.UInt64(),
        "geolocation/stale_return_flag": pl.UInt8(),
        "l2_quality_flag": pl.UInt8(),
        "land_cover_data/landsat_treecover": pl.Float64(),
        "land_cover_data/landsat_water_persistence": pl.UInt8(),
        "land_cover_data/leaf_off_doy": pl.Int16(),
        "land_cover_data/leaf_off_flag": pl.UInt8(),
        "land_cover_data/leaf_on_cycle": pl.UInt8(),
        "land_cover_data/leaf_on_doy": pl.Int16(),
        "land_cover_data/pft_class": pl.UInt8(),
        "land_cover_data/region_class": pl.UInt8(),
        # "land_cover_data/shot_number": pl.UInt64(),
        # "land_cover_data/urban_focal_window_size": pl.UInt8(),
        "land_cover_data/urban_proportion": pl.UInt8(),
        # "land_cover_data/worldcover_class": pl.Int32(),
        "lat_lowestmode": pl.Float64(),
        "lon_lowestmode": pl.Float64(),
        # "master_frac": pl.Float64(),
        # "master_int": pl.UInt32(),
        "selected_algorithm": pl.UInt8(),
        "sensitivity": pl.Float32(),
        "shot_number": pl.UInt64(),
        "solar_elevation": pl.Float32(),
        "surface_flag": pl.UInt8(),
        "wsci": pl.Float32(),
        "wsci_pi_lower": pl.Float32(),
        "wsci_pi_upper": pl.Float32(),
        # "wsci_prediction/algorithm_run_flag_a1": pl.UInt8(),
        # "wsci_prediction/algorithm_run_flag_a10": pl.UInt8(),
        # "wsci_prediction/algorithm_run_flag_a2": pl.UInt8(),
        # "wsci_prediction/algorithm_run_flag_a3": pl.UInt8(),
        # "wsci_prediction/algorithm_run_flag_a4": pl.UInt8(),
        # "wsci_prediction/algorithm_run_flag_a5": pl.UInt8(),
        # "wsci_prediction/algorithm_run_flag_a6": pl.UInt8(),
        # "wsci_prediction/l2_quality_flag_a1": pl.UInt8(),
        # "wsci_prediction/l2_quality_flag_a10": pl.UInt8(),
        # "wsci_prediction/l2_quality_flag_a2": pl.UInt8(),
        # "wsci_prediction/l2_quality_flag_a3": pl.UInt8(),
        # "wsci_prediction/l2_quality_flag_a4": pl.UInt8(),
        # "wsci_prediction/l2_quality_flag_a5": pl.UInt8(),
        # "wsci_prediction/l2_quality_flag_a6": pl.UInt8(),
        # "wsci_prediction/shot_number": pl.UInt64(),
        # "wsci_prediction/wsci_a1": pl.Float32(),
        # "wsci_prediction/wsci_a10": pl.Float32(),
        # "wsci_prediction/wsci_a2": pl.Float32(),
        # "wsci_prediction/wsci_a3": pl.Float32(),
        # "wsci_prediction/wsci_a4": pl.Float32(),
        # "wsci_prediction/wsci_a5": pl.Float32(),
        # "wsci_prediction/wsci_a6": pl.Float32(),
        # "wsci_prediction/wsci_pi_lower_a1": pl.Float32(),
        # "wsci_prediction/wsci_pi_lower_a10": pl.Float32(),
        # "wsci_prediction/wsci_pi_lower_a2": pl.Float32(),
        # "wsci_prediction/wsci_pi_lower_a3": pl.Float32(),
        # "wsci_prediction/wsci_pi_lower_a4": pl.Float32(),
        # "wsci_prediction/wsci_pi_lower_a5": pl.Float32(),
        # "wsci_prediction/wsci_pi_lower_a6": pl.Float32(),
        # "wsci_prediction/wsci_pi_upper_a1": pl.Float32(),
        # "wsci_prediction/wsci_pi_upper_a10": pl.Float32(),
        # "wsci_prediction/wsci_pi_upper_a2": pl.Float32(),
        # "wsci_prediction/wsci_pi_upper_a3": pl.Float32(),
        # "wsci_prediction/wsci_pi_upper_a4": pl.Float32(),
        # "wsci_prediction/wsci_pi_upper_a5": pl.Float32(),
        # "wsci_prediction/wsci_pi_upper_a6": pl.Float32(),
        # "wsci_prediction/wsci_quality_flag_a1": pl.UInt8(),
        # "wsci_prediction/wsci_quality_flag_a10": pl.UInt8(),
        # "wsci_prediction/wsci_quality_flag_a2": pl.UInt8(),
        # "wsci_prediction/wsci_quality_flag_a3": pl.UInt8(),
        # "wsci_prediction/wsci_quality_flag_a4": pl.UInt8(),
        # "wsci_prediction/wsci_quality_flag_a5": pl.UInt8(),
        # "wsci_prediction/wsci_quality_flag_a6": pl.UInt8(),
        # "wsci_prediction/wsci_xy_a1": pl.Float32(),
        # "wsci_prediction/wsci_xy_a10": pl.Float32(),
        # "wsci_prediction/wsci_xy_a2": pl.Float32(),
        # "wsci_prediction/wsci_xy_a3": pl.Float32(),
        # "wsci_prediction/wsci_xy_a4": pl.Float32(),
        # "wsci_prediction/wsci_xy_a5": pl.Float32(),
        # "wsci_prediction/wsci_xy_a6": pl.Float32(),
        # "wsci_prediction/wsci_xy_pi_lower_a1": pl.Float32(),
        # "wsci_prediction/wsci_xy_pi_lower_a10": pl.Float32(),
        # "wsci_prediction/wsci_xy_pi_lower_a2": pl.Float32(),
        # "wsci_prediction/wsci_xy_pi_lower_a3": pl.Float32(),
        # "wsci_prediction/wsci_xy_pi_lower_a4": pl.Float32(),
        # "wsci_prediction/wsci_xy_pi_lower_a5": pl.Float32(),
        # "wsci_prediction/wsci_xy_pi_lower_a6": pl.Float32(),
        # "wsci_prediction/wsci_xy_pi_upper_a1": pl.Float32(),
        # "wsci_prediction/wsci_xy_pi_upper_a10": pl.Float32(),
        # "wsci_prediction/wsci_xy_pi_upper_a2": pl.Float32(),
        # "wsci_prediction/wsci_xy_pi_upper_a3": pl.Float32(),
        # "wsci_prediction/wsci_xy_pi_upper_a4": pl.Float32(),
        # "wsci_prediction/wsci_xy_pi_upper_a5": pl.Float32(),
        # "wsci_prediction/wsci_xy_pi_upper_a6": pl.Float32(),
        # "wsci_prediction/wsci_z_a1": pl.Float32(),
        # "wsci_prediction/wsci_z_a10": pl.Float32(),
        # "wsci_prediction/wsci_z_a2": pl.Float32(),
        # "wsci_prediction/wsci_z_a3": pl.Float32(),
        # "wsci_prediction/wsci_z_a4": pl.Float32(),
        # "wsci_prediction/wsci_z_a5": pl.Float32(),
        # "wsci_prediction/wsci_z_a6": pl.Float32(),
        # "wsci_prediction/wsci_z_pi_lower_a1": pl.Float32(),
        # "wsci_prediction/wsci_z_pi_lower_a10": pl.Float32(),
        # "wsci_prediction/wsci_z_pi_lower_a2": pl.Float32(),
        # "wsci_prediction/wsci_z_pi_lower_a3": pl.Float32(),
        # "wsci_prediction/wsci_z_pi_lower_a4": pl.Float32(),
        # "wsci_prediction/wsci_z_pi_lower_a5": pl.Float32(),
        # "wsci_prediction/wsci_z_pi_lower_a6": pl.Float32(),
        # "wsci_prediction/wsci_z_pi_upper_a1": pl.Float32(),
        # "wsci_prediction/wsci_z_pi_upper_a10": pl.Float32(),
        # "wsci_prediction/wsci_z_pi_upper_a2": pl.Float32(),
        # "wsci_prediction/wsci_z_pi_upper_a3": pl.Float32(),
        # "wsci_prediction/wsci_z_pi_upper_a4": pl.Float32(),
        # "wsci_prediction/wsci_z_pi_upper_a5": pl.Float32(),
        # "wsci_prediction/wsci_z_pi_upper_a6": pl.Float32(),
        "wsci_quality_flag": pl.UInt8(),
        "wsci_xy": pl.Float32(),
        "wsci_xy_pi_lower": pl.Float32(),
        "wsci_xy_pi_upper": pl.Float32(),
        "wsci_z": pl.Float32(),
        "wsci_z_pi_lower": pl.Float32(),
        "wsci_z_pi_upper": pl.Float32(),
    }
)
